import { Toaster } from '@/components/ui/toaster';
import '../globals.css';
import { cn } from '@/lib/utils';

import { Inter as FontSans } from "next/font/google"
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("relative h-full antialiased font-sans", fontSans.variable)}>
      <main className='relative flex min-h-screen'>
          <section className="flex flex-1 justify-center items-center flex-col py-10">
              {children}
          </section>
          <img
            src="/illustration.png"
            alt="logo"
            className="hidden lg:block h-screen w-1/2 object-cover bg-no-repeat"
          />
        </main>
        <Toaster/>
      </body>
    </html>
  )
}
