import '../globals.css';
import { Providers } from '../providers';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className='flex'>
          <section className="flex flex-1 justify-center items-center flex-col py-10">
            <Providers>
              {children}
            </Providers>
          </section>
          <img
            src="/illustration.png"
            alt="logo"
            className="hidden lg:block h-screen w-1/2 object-cover bg-no-repeat"
          />
        </div>
      </body>
    </html>
  )
}
