import type { Metadata } from 'next'
import "../globals.css"
import { Inter as FontSans } from "next/font/google"
import Navbar from '@/components/Navbar'
import { cn } from '@/lib/utils'
import { AuthProvider } from '@/contexts/AuthContext'
 
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("relative h-full antialiased font-sans", fontSans.variable)}>
        <main className='relative flex flex-col min-h-screen'>
          <AuthProvider>
            <Navbar />
          </AuthProvider>
          <div className='flex-grow flex-1'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
